site_name: thdlrt CsNotes
repo_url: https://github.com/thdlrt/CsNotes
repo_name: thdlrt/CsNotes
theme:
  logo: https://thdlrt.oss-cn-beijing.aliyuncs.com/android-chrome-512x512.png
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
  - content.code.select
  - navigation.tabs
  - search.suggest
  - search.share
  - navigation.top
  palette:

    # Light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: light blue
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

    # Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: light blue
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode


markdown_extensions:
- footnotes
  # - attr_list
- pymdownx.arithmatex:
    generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
- pymdownx.tasklist:
    custom_checkbox: true
- def_list
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format

- toc:
    permalink: true

plugins:
  - search
  - roamlinks
  - blog:
      blog_toc: true
      post_date_format: full
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft_if_future_date: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
